name: Pushes flavor-service to another repository (develop)

on:
  push:
    branches: [ develop ]
    paths:
      - 'flavor-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Pushes flavor-service to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY_FLAVOR_SERVICE }}
        with:
          source-directory: 'flavor-service'
          destination-github-username: 'rafaeljdesa'
          destination-repository-name: 'coffe-explorer-flavor-service'
          user-email: 'rafaeljdsb1@gmail.com'
          target-branch: 'develop'
